apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: soc-app-ingress

spec:
  ingressClassName: gce

  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: soc-frontend-service
            port:
              number: 80